# src/main/resources/application.yml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtexample?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC